### PR TITLE
add loafoe/mattermost-client#118

### PR DESCRIPTION
**Pull request by mlmnetcologne**
this is the same capability as in loafoe/mattermost-client#118
Please check line 131. Are chunks necessary?

Makes possible that the client can trigger commands in a spezific channel.

usage post.postCommand('/command','channel_id')

### CODE REVIEW

**Review by DanielRuf — CHANGES_REQUESTED** [review]
Please check the linting errors and resolve them, thanks =)

**Comment by mlmnetcologne** [comment]
What are linting errors? (ginge auch auf deutsch)

**Comment by DanielRuf** [comment]
> What are linting errors? (ginge auch auf deutsch) @DanielRuf

code style violations (and code smells sometimes)

**Comment by mlmnetcologne** [comment]
sorry

**Pull request merged**
