### PR TITLE
Run CI also on latest Node version

### PR DESCRIPTION
**Pull request by DanielRuf**
Let's test it on Node latest (currently 13 atm) too.

### CODE REVIEW

**Comment by DanielRuf** [comment]
It seems there is some issue with GitHub Actions and Docker now. So let's wait until GitHub fixes this.

**Comment by HagenMorano** [comment]
Any progress on this?

**Comment by DanielRuf** [comment]
No reply from GitHub so far.

**Comment by DanielRuf** [comment]
Seems `'*'` as version does work. But this is not really documented.
https://github.com/actions/setup-node/issues/61

**Pull request merged**
